"""Initial migration for Helm AI database

Revision ID: 001
Revises: 
Create Date: 2026-01-29 16:40:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types for PostgreSQL
    op.execute("CREATE TYPE user_status AS ENUM ('active', 'inactive', 'suspended', 'pending')")
    op.execute("CREATE TYPE user_role AS ENUM ('user', 'admin', 'moderator', 'developer', 'analyst')")
    op.execute("CREATE TYPE api_key_status AS ENUM ('active', 'inactive', 'suspended', 'expired')")
    op.execute("CREATE TYPE api_key_scope AS ENUM ('read', 'write', 'admin', 'analytics', 'integrations')")
    op.execute("CREATE TYPE audit_action AS ENUM ('create', 'read', 'update', 'delete', 'login', 'logout', 'failed_login', 'password_change', 'api_key_create', 'api_key_delete', 'permission_change', 'role_change', 'export', 'import', 'system_config', 'security_event')")
    op.execute("CREATE TYPE audit_severity AS ENUM ('low', 'medium', 'high', 'critical')")
    op.execute("CREATE TYPE audit_category AS ENUM ('authentication', 'authorization', 'data_access', 'system_admin', 'security', 'compliance', 'api_usage', 'user_management', 'integration')")
    op.execute("CREATE TYPE security_event_type AS ENUM ('login_failure', 'login_success', 'logout', 'password_change', 'password_reset', 'account_lockout', 'account_unlock', 'api_key_created', 'api_key_deleted', 'api_key_suspended', 'permission_escalation', 'role_change', 'suspicious_activity', 'threat_detected', 'brute_force_attempt', 'rate_limit_exceeded', 'anomalous_behavior', 'data_breach_attempt', 'system_compromise', 'malicious_request', 'unauthorized_access')")
    op.execute("CREATE TYPE security_severity AS ENUM ('info', 'low', 'medium', 'high', 'critical')")
    op.execute("CREATE TYPE threat_type AS ENUM ('brute_force', 'credential_stuffing', 'sql_injection', 'xss_attack', 'csrf_attack', 'dos_attack', 'malware', 'phishing', 'insider_threat', 'data_exfiltration', 'account_takeover', 'api_abuse', 'unauthorized_api', 'suspicious_pattern')")
    op.execute("CREATE TYPE event_status AS ENUM ('new', 'investigating', 'resolved', 'false_positive', 'ignored')")
    op.execute("CREATE TYPE game_session_status AS ENUM ('active', 'completed', 'aborted', 'disconnected', 'suspended', 'banned')")
    op.execute("CREATE TYPE game_type AS ENUM ('poker', 'blackjack', 'roulette', 'slots', 'sports_betting', 'esports', 'custom')")
    op.execute("CREATE TYPE cheat_detection_status AS ENUM ('clean', 'suspicious', 'detected', 'investigating', 'confirmed', 'false_positive')")
    
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('auth_provider', sa.String(length=50), nullable=True),
        sa.Column('provider_id', sa.String(length=255), nullable=True),
        sa.Column('status', postgresql.ENUM(user_status), nullable=True),
        sa.Column('role', postgresql.ENUM(user_role), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=True),
        sa.Column('plan', sa.String(length=50), nullable=True),
        sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
        sa.Column('trial_expires_at', sa.DateTime(), nullable=True),
        sa.Column('company', sa.String(length=255), nullable=True),
        sa.Column('job_title', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=True),
        sa.Column('language', sa.String(length=10), nullable=True),
        sa.Column('preferences', sa.JSON(), nullable=True),
        sa.Column('notification_settings', sa.JSON(), nullable=True),
        sa.Column('last_login_at', sa.DateTime(), nullable=True),
        sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
        sa.Column('locked_until', sa.DateTime(), nullable=True),
        sa.Column('password_changed_at', sa.DateTime(), nullable=True),
        sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
        sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('pk_users'),
        sa.UniqueConstraint('uq_users_email'),
        sa.UniqueConstraint('uq_users_username')
    )
    op.create_index('ix_users_email', 'users', ['email'])
    op.create_index('ix_users_username', 'users', ['username'])
    op.create_index('ix_users_status', 'users', ['status'])
    op.create_index('ix_users_role', 'users', ['role'])
    op.create_index('ix_users_created_at', 'users', ['created_at'])
    
    # Create api_keys table
    op.create_table('api_keys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key_id', sa.String(length=64), nullable=False),
        sa.Column('key_hash', sa.String(length=255), nullable=False),
        sa.Column('key_prefix', sa.String(length=8), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', postgresql.ENUM(api_key_status), nullable=True),
        sa.Column('scopes', sa.JSON(), nullable=True),
        sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
        sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
        sa.Column('rate_limit_per_day', sa.Integer(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('total_requests', sa.Integer(), nullable=True),
        sa.Column('allowed_ips', sa.JSON(), nullable=True),
        sa.Column('allowed_domains', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint('fk_api_keys_user_id', 'users', ['id'], ),
        sa.PrimaryKeyConstraint('pk_api_keys'),
        sa.UniqueConstraint('uq_api_keys_key_id')
    )
    op.create_index('ix_api_keys_key_id', 'api_keys', ['key_id'])
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'])
    op.create_index('ix_api_keys_status', 'api_keys', ['status'])
    op.create_index('ix_api_keys_expires_at', 'api_keys', ['expires_at'])
    
    # Create audit_logs table
    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', postgresql.ENUM(audit_action), nullable=False),
        sa.Column('category', postgresql.ENUM(audit_category), nullable=False),
        sa.Column('severity', postgresql.ENUM(audit_severity), nullable=True),
        sa.Column('resource_type', sa.String(length=100), nullable=True),
        sa.Column('resource_id', sa.String(length=255), nullable=True),
        sa.Column('resource_name', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('request_id', sa.String(length=64), nullable=True),
        sa.Column('session_id', sa.String(length=64), nullable=True),
        sa.Column('api_key_id', sa.String(length=64), nullable=True),
        sa.Column('endpoint', sa.String(length=255), nullable=True),
        sa.Column('http_method', sa.String(length=10), nullable=True),
        sa.Column('http_status_code', sa.Integer(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('error_code', sa.String(length=100), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('compliance_tags', sa.JSON(), nullable=True),
        sa.Column('retention_days', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint('fk_audit_logs_user_id', 'users', ['id'], ),
        sa.PrimaryKeyConstraint('pk_audit_logs')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'])
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'])
    op.create_index('ix_audit_logs_category', 'audit_logs', ['category'])
    op.create_index('ix_audit_logs_severity', 'audit_logs', ['severity'])
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'])
    op.create_index('ix_audit_logs_resource_id', 'audit_logs', ['resource_id'])
    op.create_index('ix_audit_logs_ip_address', 'audit_logs', ['ip_address'])
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'])
    op.create_index('ix_audit_logs_session_id', 'audit_logs', ['session_id'])
    op.create_index('ix_audit_logs_api_key_id', 'audit_logs', ['api_key_id'])
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'])
    
    # Create api_usage_logs table
    op.create_table('api_usage_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('api_key_id', sa.String(length=64), nullable=False),
        sa.Column('endpoint', sa.String(length=255), nullable=False),
        sa.Column('http_method', sa.String(length=10), nullable=False),
        sa.Column('http_status_code', sa.Integer(), nullable=False),
        sa.Column('request_timestamp', sa.DateTime(), nullable=False),
        sa.Column('duration_ms', sa.Integer(), nullable=False),
        sa.Column('request_size_bytes', sa.Integer(), nullable=True),
        sa.Column('response_size_bytes', sa.Integer(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('request_id', sa.String(length=64), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint('fk_api_usage_logs_api_key_id', 'api_keys', ['key_id'], ),
        sa.PrimaryKeyConstraint('pk_api_usage_logs')
    )
    op.create_index('ix_api_usage_logs_api_key_id', 'api_usage_logs', ['api_key_id'])
    op.create_index('ix_api_usage_logs_endpoint', 'api_usage_logs', ['endpoint'])
    op.create_index('ix_api_usage_logs_http_method', 'api_usage_logs', ['http_method'])
    op.create_index('ix_api_usage_logs_http_status_code', 'api_usage_logs', ['http_status_code'])
    op.create_index('ix_api_usage_logs_request_timestamp', 'api_usage_logs', ['request_timestamp'])
    op.create_index('ix_api_usage_logs_ip_address', 'api_usage_logs', ['ip_address'])
    
    # Create security_events table
    op.create_table('security_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('event_type', postgresql.ENUM(security_event_type), nullable=False),
        sa.Column('severity', postgresql.ENUM(security_severity), nullable=False),
        sa.Column('threat_type', postgresql.ENUM(threat_type), nullable=True),
        sa.Column('status', postgresql.ENUM(event_status), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('source_ip', sa.String(length=45), nullable=True),
        sa.Column('source_country', sa.String(length=2), nullable=True),
        sa.Column('source_user_agent', sa.Text(), nullable=True),
        sa.Column('source_api_key', sa.String(length=64), nullable=True),
        sa.Column('target_resource', sa.String(length=255), nullable=True),
        sa.Column('target_user_id', sa.Integer(), nullable=True),
        sa.Column('target_endpoint', sa.String(length=255), nullable=True),
        sa.Column('detection_method', sa.String(length=100), nullable=True),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('region', sa.String(length=100), nullable=True),
        sa.Column('occurred_at', sa.DateTime(), nullable=False),
        sa.Column('detected_at', sa.DateTime(), nullable=False),
        sa.Column('assigned_to', sa.Integer(), nullable=True),
        sa.Column('investigation_notes', sa.Text(), nullable=True),
        sa.Column('resolution_notes', sa.Text(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('resolved_by', sa.Integer(), nullable=True),
        sa.Column('auto_response_taken', sa.Boolean(), nullable=True),
        sa.Column('auto_response_details', sa.JSON(), nullable=True),
        sa.Column('parent_event_id', sa.Integer(), nullable=True),
        sa.Column('related_events', sa.JSON(), nullable=True),
        sa.Column('compliance_tags', sa.JSON(), nullable=True),
        sa.Column('requires_reporting', sa.Boolean(), nullable=True),
        sa.Column('reported_at', sa.DateTime(), nullable=True),
        sa.Column('retention_days', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint('fk_security_events_user_id', 'users', ['id'], ),
        sa.ForeignKeyConstraint('fk_security_events_target_user_id', 'users', ['id'], ),
        sa.ForeignKeyConstraint('fk_security_events_assigned_to', 'users', ['id'], ),
        sa.ForeignKeyConstraint('fk_security_events_resolved_by', 'users', ['id'], ),
        sa.ForeignKeyConstraint('fk_security_events_parent_event_id', 'security_events', ['id'], ),
        sa.PrimaryKeyConstraint('pk_security_events')
    )
    op.create_index('ix_security_events_user_id', 'security_events', ['user_id'])
    op.create_index('ix_security_events_event_type', 'security_events', ['event_type'])
    op.create_index('ix_security_events_severity', 'security_events', ['severity'])
    op.create_index('ix_security_events_threat_type', 'security_events', ['threat_type'])
    op.create_index('ix_security_events_status', 'security_events', ['status'])
    op.create_index('ix_security_events_source_ip', 'security_events', ['source_ip'])
    op.create_index('ix_security_events_occurred_at', 'security_events', ['occurred_at'])
    op.create_index('ix_security_events_detected_at', 'security_events', ['detected_at'])
    op.create_index('ix_security_events_assigned_to', 'security_events', ['assigned_to'])
    op.create_index('ix_security_events_resolved_by', 'security_events', ['resolved_by'])
    
    # Create game_sessions table
    op.create_table('game_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=128), nullable=False),
        sa.Column('game_type', postgresql.ENUM(game_type), nullable=False),
        sa.Column('game_variant', sa.String(length=100), nullable=True),
        sa.Column('status', postgresql.ENUM(game_session_status), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('ended_at', sa.DateTime(), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('table_id', sa.String(length=100), nullable=True),
        sa.Column('tournament_id', sa.String(length=100), nullable=True),
        sa.Column('stake_level', sa.String(length=50), nullable=True),
        sa.Column('buy_in_amount', sa.Float(), nullable=True),
        sa.Column('currency', sa.String(length=10), nullable=True),
        sa.Column('player_name', sa.String(length=100), nullable=True),
        sa.Column('player_avatar', sa.String(length=255), nullable=True),
        sa.Column('player_level', sa.Integer(), nullable=True),
        sa.Column('player_rank', sa.String(length=50), nullable=True),
        sa.Column('client_ip', sa.String(length=45), nullable=True),
        sa.Column('client_country', sa.String(length=2), nullable=True),
        sa.Column('client_user_agent', sa.Text(), nullable=True),
        sa.Column('client_version', sa.String(length=50), nullable=True),
        sa.Column('platform', sa.String(length=50), nullable=True),
        sa.Column('total_actions', sa.Integer(), nullable=True),
        sa.Column('total_hands', sa.Integer(), nullable=True),
        sa.Column('total_winnings', sa.Float(), nullable=True),
        sa.Column('total_losses', sa.Float(), nullable=True),
        sa.Column('net_profit', sa.Float(), nullable=True),
        sa.Column('win_rate', sa.Float(), nullable=True),
        sa.Column('avg_decision_time_ms', sa.Float(), nullable=True),
        sa.Column('avg_bet_size', sa.Float(), nullable=True),
        sa.Column('max_bet_size', sa.Float(), nullable=True),
        sa.Column('variance_score', sa.Float(), nullable=True),
        sa.Column('aggression_score', sa.Float(), nullable=True),
        sa.Column('cheat_detection_status', postgresql.ENUM(cheat_detection_status), nullable=True),
        sa.Column('cheat_confidence_score', sa.Float(), nullable=True),
        sa.Column('cheat_types_detected', sa.JSON(), nullable=True),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column('flagged_at', sa.DateTime(), nullable=True),
        sa.Column('investigated_at', sa.DateTime(), nullable=True),
        sa.Column('ai_analysis', sa.JSON(), nullable=True),
        sa.Column('vision_analysis', sa.JSON(), nullable=True),
        sa.Column('audio_analysis', sa.JSON(), nullable=True),
        sa.Column('network_analysis', sa.JSON(), nullable=True),
        sa.Column('manual_review_required', sa.Boolean(), nullable=True),
        sa.Column('manual_review_by', sa.Integer(), nullable=True),
        sa.Column('manual_review_notes', sa.Text(), nullable=True),
        sa.Column('manual_review_at', sa.DateTime(), nullable=True),
        sa.Column('actions_taken', sa.JSON(), nullable=True),
        sa.Column('ban_reason', sa.Text(), nullable=True),
        sa.Column('ban_expires_at', sa.DateTime(), nullable=True),
        sa.Column('events', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint('fk_game_sessions_user_id', 'users', ['id'], ),
        sa.ForeignKeyConstraint('fk_game_sessions_manual_review_by', 'users', ['id'], ),
        sa.PrimaryKeyConstraint('pk_game_sessions'),
        sa.UniqueConstraint('uq_game_sessions_session_id')
    )
    op.create_index('ix_game_sessions_user_id', 'game_sessions', ['user_id'])
    op.create_index('ix_game_sessions_session_id', 'game_sessions', ['session_id'])
    op.create_index('ix_game_sessions_game_type', 'game_sessions', ['game_type'])
    op.create_index('ix_game_sessions_status', 'game_sessions', ['status'])
    op.create_index('ix_game_sessions_started_at', 'game_sessions', ['started_at'])
    op.create_index('ix_game_sessions_ended_at', 'game_sessions', ['ended_at'])
    op.create_index('ix_game_sessions_client_ip', 'game_sessions', ['client_ip'])
    op.create_index('ix_game_sessions_cheat_detection_status', 'game_sessions', ['cheat_detection_status'])
    op.create_index('ix_game_sessions_risk_score', 'game_sessions', ['risk_score'])
    op.create_index('ix_game_sessions_flagged_at', 'game_sessions', ['flagged_at'])
    
    # ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order
    op.drop_table('game_sessions')
    op.drop_table('security_events')
    op.drop_table('api_usage_logs')
    op.drop_table('audit_logs')
    op.drop_table('api_keys')
    op.drop_table('users')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS cheat_detection_status")
    op.execute("DROP TYPE IF EXISTS game_type")
    op.execute("DROP TYPE IF EXISTS game_session_status")
    op.execute("DROP TYPE IF EXISTS event_status")
    op.execute("DROP TYPE IF EXISTS threat_type")
    op.execute("DROP TYPE IF EXISTS security_severity")
    op.execute("DROP TYPE IF EXISTS security_event_type")
    op.execute("DROP TYPE IF EXISTS audit_category")
    op.execute("DROP TYPE IF EXISTS audit_severity")
    op.execute("DROP TYPE IF EXISTS audit_action")
    op.execute("DROP TYPE IF EXISTS api_key_scope")
    op.execute("DROP TYPE IF EXISTS api_key_status")
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP TYPE IF EXISTS user_status")
